### ISSUE TITLE
Does supabase authentication work when packaged/bundled?

### ISSUE THREAD

**Issue by kentezrabetita** [Jgrtowy/PolyBase#1]

**Comment by Jgrtowy** [comment]
Fixed, patch will be implemented in next commit 👍

**Comment by kentezrabetita** [comment]
@Jgrtowy Great! Whenever you have a chance, could you please add a demo as well? Thank you!

**Comment by Jgrtowy** [comment]
@kentezrabetita Of course! This is already on my roadmap so stay tuned!
